#ifndef SYJ_EDGEMIND_DASHBOARD_STATIC_H
#define SYJ_EDGEMIND_DASHBOARD_STATIC_H

namespace syj::edgemind::dashboard {

inline constexpr const char kDashboardHtml[] = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SYJ EdgeMind — Local Operations</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#e8edf5;background:#0b1020}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#17244b 0,#0b1020 45%);min-height:100vh}.wrap{max-width:1180px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:20px}.brand{font-size:22px;font-weight:750}.sub{color:#8fa0bb;font-size:13px;margin-top:3px}.pill{border:1px solid #293653;border-radius:999px;padding:7px 12px;color:#a9bad5;font-size:12px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.card{grid-column:span 4;background:#11192b;border:1px solid #263451;border-radius:14px;padding:16px;box-shadow:0 8px 30px #0003}.wide{grid-column:span 8}.full{grid-column:1/-1}.title{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#8fa0bb;margin-bottom:12px}.value{font-size:21px;font-weight:700;word-break:break-word}.muted{color:#8fa0bb;font-size:13px}.ok{color:#67e8a5}.bad{color:#ff8d9c}.row{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid #202c43;font-size:13px}.row:last-child{border:0}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}button{background:#1b2945;color:#eef4ff;border:1px solid #324666;border-radius:9px;padding:9px 12px;cursor:pointer}button:hover{background:#243758}input,select,textarea{width:100%;background:#0c1323;color:#eef4ff;border:1px solid #2c3c5b;border-radius:8px;padding:9px;margin-top:5px}label{display:block;color:#8fa0bb;font-size:12px;margin:8px 0}.model{padding:10px 0;border-bottom:1px solid #202c43}.model:last-child{border:0}.mono{font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px;white-space:pre-wrap;overflow:auto;max-height:220px}.notice{margin:10px 0;padding:10px;border-radius:9px;background:#0d1627;border:1px solid #293955;color:#a9bad5;font-size:13px}.chat{height:280px;overflow:auto;background:#0a111f;border:1px solid #263451;border-radius:10px;padding:12px}.msg{margin:7px 0;white-space:pre-wrap}.me{color:#b8c9ff}.ai{color:#8ee8b4}@media(max-width:850px){.card,.wide{grid-column:1/-1}}
</style></head><body><div class="wrap">
<div class="top"><div><div class="brand">SYJ EdgeMind</div><div class="sub">Local Operations Dashboard · C API boundary · localhost only</div></div><div class="pill" id="conn">Connecting…</div></div>
<div class="grid">
<div class="card"><div class="title">Runtime</div><div class="value" id="runtime">—</div><div class="muted" id="model">—</div><div class="actions"><button onclick="post('/api/runtime/unload')">Unload</button><button onclick="post('/api/runtime/reload')">Reload</button><button onclick="post('/api/runtime/reset')">Reset context</button></div></div>
<div class="card"><div class="title">System memory</div><div class="value" id="mem">—</div><div class="muted" id="memdetail">—</div></div>
<div class="card"><div class="title">API</div><div class="value" id="abi">—</div><div class="muted" id="version">—</div></div>
<div class="card wide"><div class="title">Models</div><div id="models" class="muted">Loading…</div></div>
<div class="card"><div class="title">Load model</div><label>Model ID<input id="model_id" placeholder="64-char SHA-256 (preferred)"></label><label>Or local GGUF path<input id="model_path" placeholder="/path/to/model.gguf"></label><label>Context<input id="context" type="number" value="1024" min="16" max="8192"></label><label>Threads<input id="threads" type="number" value="4" min="1"></label><div class="actions"><button onclick="loadModel()">Load</button></div></div>
<div class="card wide"><div class="title">Generation</div><div class="chat" id="chat"></div><textarea id="prompt" rows="3" placeholder="Ask the local model…"></textarea><div class="actions"><button onclick="generate()">Generate</button></div></div>
<div class="card full"><div class="title">Diagnostics</div><div class="row"><span>Memory admission</span><span class="mono" id="memory_report">—</span></div><div class="row"><span>Usage / quota</span><span class="mono" id="usage_report">—</span></div></div>
</div><div class="notice">Security posture: the server binds to 127.0.0.1 and requires the bearer token printed by the process at startup. It exposes runtime operations only; there is no filesystem or shell endpoint.</div></div>
<script>
const token=sessionStorage.getItem('syj_token')||prompt('Enter the SYJ EdgeMind dashboard bearer token'); if(token)sessionStorage.setItem('syj_token',token);
async function api(path,opt={}){opt.headers=Object.assign({'Authorization':'Bearer '+(sessionStorage.getItem('syj_token')||'')},opt.headers||{});const r=await fetch(path,opt);if(!r.ok)throw new Error((await r.text())||r.status);return r}
async function get(path){return (await api(path)).json()} async function post(path,body){try{const r=await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:body||'{}'});const j=await r.json();if(j.message)alert(j.message);refresh()}catch(e){alert(e.message)}}
function text(id,v){document.getElementById(id).textContent=v}
async function refresh(){try{const [h,v,s,m,r,mem,u]=await Promise.all([get('/api/health'),get('/api/version'),get('/api/system'),get('/api/models'),get('/api/runtime'),get('/api/memory'),get('/api/usage')]);text('conn',h.status);text('abi','ABI '+v.abi_version);text('version',v.release);text('runtime',r.loaded?'LOADED':'UNLOADED');text('model',r.model?.description||'No model loaded');text('mem',s.available?(Math.round(s.available_mb)+' MB available'):'unknown');text('memdetail',s.available?Math.round(s.total_mb)+' MB total':'live system memory unavailable on this platform');text('memory_report',mem.report||'No report');text('usage_report',u.report||'No report');renderModels(m.models||[])}catch(e){text('conn','AUTH / CONNECTION ERROR');console.error(e)}}
function renderModels(a){document.getElementById('models').innerHTML=a.length?a.map(x=>'<div class="model"><b>'+esc(x.name||'(unnamed)')+'</b><div class="mono">'+esc(x.model_id)+'</div><div class="muted">'+esc((x.architecture||'unknown')+' · '+(x.quantization||'unknown')+' · '+(x.verification||'unknown'))+'</div><button onclick="selectModel(\''+esc(x.model_id)+'\')">Select</button></div>').join(''):'No registered models.'}
function selectModel(id){document.getElementById('model_id').value=id;document.getElementById('model_path').value=''} function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadModel(){const body={model_id:document.getElementById('model_id').value||undefined,model_path:document.getElementById('model_path').value||undefined,context_size:+document.getElementById('context').value,threads:+document.getElementById('threads').value};await post('/api/runtime/load',JSON.stringify(body))}
async function generate(){const p=document.getElementById('prompt').value;if(!p)return;const c=document.getElementById('chat');c.insertAdjacentHTML('beforeend','<div class="msg me">'+esc(p)+'</div><div class="msg ai" id="stream"></div>');const out=document.getElementById('stream');try{const r=await api('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p})});const reader=r.body.getReader(),dec=new TextDecoder();while(true){const x=await reader.read();if(x.done)break;for(const line of dec.decode(x.value,{stream:true}).split('\n'))if(line.startsWith('data: ')){try{out.textContent+=JSON.parse(line.slice(6)).token}catch(_){}}}document.getElementById('prompt').value='';refresh()}catch(e){out.textContent+='\n[error] '+e.message}}
refresh();setInterval(refresh,2500);
</script></body></html>)HTML";

} // namespace syj::edgemind::dashboard

#endif // SYJ_EDGEMIND_DASHBOARD_STATIC_H
